### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by ersin-ertan** [dmkoelle/jfugue#2]
I am going to provide an examples folder, are the examples from http://www.jfugue.org/examples.html updated for the 5.0 release?

**Comment by dmkoelle** [comment]
Yes, those examples are up-to-date for the latest release.

**Comment by ersin-ertan** [comment]
Ok, I have found the examples folder that you have mentioned. Should I leave the file structure in the github repo the same and simply add/override the files with the files from the examples/website. Or should I use the /examples/java/org/jfugue/examples/website/ structure and restructure what is in the repo?
